### ISSUE TITLE
Remove all trailing commas?

### ISSUE THREAD

**Issue by TylerYep** [asottile/add-trailing-comma#102]
This is probably a strange ask, but I am working on a project that requires all trailing commas in Python code to be removed. I was wondering if there was a way to achieve that goal with a few tweaks to this codebase?

I haven't looked very closely at the code, but I figured I would ask first to save myself some time if it was infeasible. Thanks!

**Comment by asottile** [comment]
lol, is this a joke?

**Comment by TylerYep** [comment]
No, this is not a joke, I'm actually working on a project to analyze the distribution of line lengths in Python code generated by Black, and since Black now automatically adds trailing commas, I am looking for way to undo that.

Sorry if I didn't include enough detail in the comment - I didn't mean for this to be feature request, just wanted to get your opinion on this.

**Comment by asottile** [comment]
sure it's possible, the technique I use here isn't exactly novel -- tokenize, ast parse, cross reference, find the things that could be comma-able and add commas

you'd essentially do the same thing except remove them (but look out for 1-element tuples!)
