### ISSUE TITLE
Is it possible to run this on Kotlin projects?

### ISSUE THREAD

**Issue by alexanderbezverhni** [asottile/add-trailing-comma#108]
As of recent update, Kotlin supports trailing commas. I wonder if it would be possible to use this tool to add trailing commas all over Kotlin/Android project?

**Comment by Mause** [comment]
This project is specifically for python?

**Comment by asottile** [comment]
this project is specifically for python -- if you could produce a similar ast / tokenizing parser for kotlin it would be possible -- but likely out of scope for this project
