### ISSUE TITLE
Multiline string issue

### ISSUE THREAD

**Issue by SUNx2YCH** [asottile/add-trailing-comma#118]
Doesn't really break the code (at least in my case), but looks like a bug:
```diff
logger.info(
    'one'
-   'two'
+   'two',
)
```

**Comment by asottile** [comment]
it is intentional, all multiline functions (even if they only have one argument) will receive trailing commas

**Comment by SUNx2YCH** [comment]
Ah, my bad. But for such strings it looks especially weird :)

**Comment by asottile** [comment]
no special cases, as soon as you start discussion special cases opinions creep in
