### ISSUE TITLE
Disable change to dangling commas on imports

### ISSUE THREAD

**Issue by lynxoid** [asottile/add-trailing-comma#122]
We are using `add-trailing-comma` for dangling commas and `isort` to keep our imports organized. Ideally, both can run as pre-commit hooks. However, the two tools clash on statements like this:

```
from my_library.api.database.models import (Model1, Model2, Model3, Model4, Model5, Model6
                                            Model7,)
```
where `isort` prefers this style and `add-trailing-comma` reformats it into:
```
from my_library.api.database.models import (
    Model1, Model2, Model3, Model4, Model5, Model6
    Model7,
)
```
When trying to commit, no matter the order between `isort` and `add-trailing-comma`, the imports are always re-arranged, preventing commit. Disabling `add-trailing-comma` on imports would allow us to run isort and to use your tool for other parts of the file.

**Comment by asottile** [comment]
you're looking for the `include_trailing_comma` option to `isort`

**Comment by asottile** [comment]
or `profile = black` will also work

**Comment by lynxoid** [comment]
Thanks! We already had `include_trailing_comma=True`, but adding `profile=black` solved it.

**Comment by asottile** [comment]
cheers!  glad that helped!
