### ISSUE TITLE
Trailing comma for function which enforces keyword arguments (`f(*, a, b, ...)`)

### ISSUE THREAD

**Issue by geo7** [asottile/add-trailing-comma#131]
Didn't initially realise that args had to be on separate lines for functions in order for `add-trailing-comma` to modify (in original comment). Realised that and added to `# edit`. 

--------

# original comment

```
# requirements.txt
appdirs==1.4.4
cfgv==3.3.0
distlib==0.3.1
filelock==3.0.12
identify==2.2.6
nodeenv==1.6.0
pre-commit==2.13.0
PyYAML==5.4.1
six==1.16.0
toml==0.10.2
virtualenv==20.4.7
```

```
#.pre-commit-config.yaml 
minimum_pre_commit_version: 2.10.0
repos:
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]
  ```

Running `pre-commit` as: `pre-commit run --all-files` I'm expecting (hoping...) with the following test file: 

```python
def A(*, a):
    return True

def B(a,b):
    return True

def C(*args):
    return True

x = [1, 2, 3]

def function_call(a, b, c):
    return True 

function_call(
    a=1, b=2, c=3
)
```

Gives the diff: 

```
diff --git a/test.py b/test.py
index 6bc7d22..edf345f 100644
--- a/test.py
+++ b/test.py
@@ -13,5 +13,5 @@ def function_call(a, b, c):
     return True

 function_call(
-    a=1, b=2, c=3
+    a=1, b=2, c=3,
 )
```

Though the diff that I was expecting (...hoping?) for was: 

```
diff --git a/test.py b/test.py
index 6bc7d22..768e441 100644
--- a/test.py
+++ b/test.py
@@ -1,17 +1,17 @@
-def A(*, a):
+def A(*, a,):
     return True

-def B(a,b):
+def B(a,b,):
     return True

-def C(*args):
+def C(*args,):
     return True

-x = [1, 2, 3]
+x = [1, 2, 3,]

-def function_call(a, b, c):
+def function_call(a, b, c,):
     return True

 function_call(
-    a=1, b=2, c=3
+    a=1, b=2, c=3,
 )
```

There's probably something that I'm missing - but having looked through the readme I'm not sure what. 

# edit

Given the following file: 

```python
def A(*, 
a):
    return True

def B(a,
b):
    return True

def C(*args
):
    return True

x = [1, 2, 3]

def function_call(a, b, 
c):
    return True 

function_call(
    a=1, b=2, c=3
)
```

the diff is as expected having run : `pre-commit run --all-files`: 

```
diff --git a/test.py b/test.py
index f37eb5c..361e427 100644
--- a/test.py
+++ b/test.py
@@ -1,21 +1,28 @@
-def A(*,
-a):
+def A(
+    *,
+    a,
+):
     return True

-def B(a,
-b):
+def B(
+    a,
+    b,
+):
     return True

-def C(*args
+def C(
+    *args,
 ):
     return True

 x = [1, 2, 3]

-def function_call(a, b,
-c):
+def function_call(
+    a, b,
+    c,
+):
     return True

 function_call(
-    a=1, b=2, c=3
+    a=1, b=2, c=3,
 )
```

Seems I didn't realise that they had to be on separate lines in order for `add-trailing-comma` to pick up on them. 

If there's a way to set this so that `add-trailing-comma` added a trailing comma to functions all the time that would be ideal.

If not then this may have shifted from an issue to a feature request and can probably be closed 😄

**Comment by asottile** [comment]
there's zero point in putting extra trailing commas inline

**Comment by geo7** [comment]
Well there is - the point being that it makes things more consistent - and that there can sometimes be a function which has a bunch of args that I'd rather on separate lines, and having the additional comma added would make black format them to separate lines.

**Comment by asottile** [comment]
if you're using black there's no point in using this

**Comment by geo7** [comment]
If trailing comma add trailing commas to the end of functions, then black would format them differently, black doesn't add the trailing commas, so won't format the functions as I'd like here. 

It might be a use-case which is outside the scope of this package, which is fine, just making sure that the reasoning was clear.

**Comment by asottile** [comment]
black absolutely does?

```python
def f(
    this,
    function,
    has,
    a,
    whole,
    bunch,
    of,
    parameters,
    but,
    theres,
    no,
    trailing,
    comma
):
    pass
```

```diff
$ venv39/bin/black --diff t2.py 
--- t2.py	2021-05-27 15:45:24.778542 +0000
+++ t2.py	2021-05-27 15:45:26.187483 +0000
@@ -9,8 +9,8 @@
     parameters,
     but,
     theres,
     no,
     trailing,
-    comma
+    comma,
 ):
     pass
would reformat t2.py
All done! ✨ 🍰 ✨
1 file would be reformatted
```

**Comment by geo7** [comment]
Didn't realise black did that, I think I've always had both black and add-trailing-comma 😅 

Given : 

```python
def f(
    this,
    function,
    has,
    a,
    whole,
    bunch,
    of,
    parameters,
    but,
    theres,
    no,
    trailing,
    comma,
):
    pass


def f(this, function, has):
    pass
```

I'd want the diff to be

```diff
diff --git a/t.py b/t.py
index 39b1f99..cbfc62b 100644
--- a/t.py
+++ b/t.py
@@ -11,10 +11,14 @@ def f(
     theres,
     no,
     trailing,
-    comma
+    comma,
 ):
     pass


-def f(this, function, has):
+def f(
+    this,
+    function,
+    has,
+):
     pass
```

Sorry if this was unclear - so the thinking was - have `add-trailing-comma` add the trailing comma, then have black format it.

**Comment by asottile** [comment]
you don't actually want that, trust me.  you'd end up with this ugly nonsense

```diff
-class C(A): pass
-
-f(1)
+class C(
+    A,
+): pass
+
+f(
+    1,
+)
```
