### ISSUE TITLE
[Question]: How to avoid adding a comma in a single line ?

### ISSUE THREAD

**Issue by diegovalenzuelaiturra** [asottile/add-trailing-comma#157]
Hi!

I've started using this tool, and the following is happening

```python3
ValueError("something ...",)
```

I'm not sure if that's desired, but I'd like to avoid adding trailing comma here.  ( It also happens in `print`s statements with a single string) - Currently `flake8-commas`[^flake8-commas] mark them as `trailing comma prohibited (C819)`. 

Is there a way to avoid adding trailing comma in specific lines ?

Thanks!

[^flake8-commas]: https://github.com/PyCQA/flake8-commas/

**Comment by asottile** [comment]
watch this and then try again: https://youtu.be/ritp4gAqNMI

add-trailing-comma actually *removes* that comma: https://github.com/asottile/add-trailing-comma#remove-unnecessary-commas

**Comment by idgserpro** [comment]
I've added a simple reproducible example at least from the `print` statement:

`$ cat print_test.py`

```python
print(
    'This is a really long string, to be used as an example for https://github.com/asottile/add-trailing-comma/issues/157.'
)
```
add-trailing-comma version: 2.4.0

```
$ add-trailing-comma print_test.py
WARNING: add-trailing-comma will only use 3.6+ mod after 3.0
Rewriting print_test.py
```
`$ cat print_test.py`

```python
print(
    'This is a really long string, to be used as an example for https://github.com/asottile/add-trailing-comma/issues/157.',
)
```

**Comment by asottile** [comment]
title says "in a single line"
