### ISSUE TITLE
Not adding trailing comma

### ISSUE THREAD

**Issue by merc1031** [asottile/add-trailing-comma#169]
I have some code that black formatted like this
```
            extended_retry_message = textwrap.dedent(
                f"""\
                {retry_message[0]}
                {retry_blurb}
            """
            )  # noqa: N400
```
another
```
                        assert all(
                            (
                                v == result["new_expectations"][k]
                                for k, v in {
                                    "jenkins_id": jn.jenkins_id,
                                }.items()
                            )
                        )

```
i have add-trailing-comma running right after black with `--py36-plus` and it doesnt add the trailing comma to that function call
```
 -   repo: https://github.com/asottile/add-trailing-comma
     rev: v2.2.1
     hooks:
     -   id: add-trailing-comma
         args: [--py36-plus]
```

**Comment by asottile** [comment]
your version of python suffers from a bug -- try upgrading to a more recent version of python: https://github.com/asottile/add-trailing-comma/blob/a7225fdeeeadbe411e9acf5d97c4fd6794a1b1d9/tests/features/calls_test.py#L56-L71

**Comment by merc1031** [comment]
@asottile Do you mean python 3.6? or a particular subversion?

also did you see my second example

**Comment by merc1031** [comment]
All the failures to add i have seen so far seem to be of those 2 forms

**Comment by asottile** [comment]
a trailing comma on a generator is another "bug" in python that's being worked around -- it introduces a common syntax error in some versions and in some parsers (particularly lib2to3-based): 

https://github.com/asottile/add-trailing-comma/blob/a7225fdeeeadbe411e9acf5d97c4fd6794a1b1d9/tests/features/calls_test.py#L16

**Comment by asottile** [comment]
I did not because you edited it in after posting -- in general you should make one bug for one bug rather than two together -- and especially don't edit in unrelated stuff after the fact:P

**Comment by merc1031** [comment]
Ah my bad.
Is it recommended then to 
a) upgrade python
b) ignore the comma after single generator argument (any particular python versions).

Thanks for the fast responses!

**Comment by asottile** [comment]
I don't care what you do, do whatever you want to do -- I'm not going to make a recommendation but just giving you the information to make your own decision
