### ISSUE TITLE
Do not add trailing comma on single parameter function calls

### ISSUE THREAD

**Issue by tomasz-kaminski** [asottile/add-trailing-comma#170]
This utility adds trailing comma to function call having a single param - yes, this is in line with the overall idea - however, I find it quite ugly. 

IMO it would be useful to skip trailing comma in cases like below. Can this be controlled by an additional parameter?

```python
logger.warning(
   f"Retry needed for http request, sleeping {wait_time} seconds.",
)
```

**Comment by tomasz-kaminski** [comment]
@asottile any explanation on why you closed this issue?

**Comment by asottile** [comment]
you did not search the issue tracker
