### ISSUE TITLE
Using pre-commit hook in combination with yapf

### ISSUE THREAD

**Issue by dietervansteenwegen** [asottile/add-trailing-comma#185]
I'm using yapf in VSC. I find that YAPF reverts changes made by the pre-commit hook:
![image](https://user-images.githubusercontent.com/46349482/170213201-c9142fb5-132c-4eba-89fc-1d0a542c2b94.png)

So when finished with a change, I commit the changes, but then the pre-commit hook undoes the changes, requiring me to add the new changes another time to the staged files.
Not a real issue as such, but I'm wondering if there is a more elegant way to handle this. 

I'm not really experienced, so I fully realize that the issue is likely on my end...

**Comment by dietervansteenwegen** [comment]
For what it's worth, this is my yapf configuration:
`    "python.formatting.yapfArgs": [
        "--style",
        "{based_on_style: pep8, column_limit: 99, indent_width: 4, spaces_before_comment = 2, split_before_logical_operator = true}"
    ],`

**Comment by asottile** [comment]
yeah the two are not generally compatible -- there's no need for atc if you're using black or yapf
