### ISSUE TITLE
Document compatibility with isort

### ISSUE THREAD

**Issue by Avasam** [asottile/add-trailing-comma#198]
Could documentation about compatibility with isort be added?
Specifically, [`multi_line_output`](https://pycqa.github.io/isort/docs/configuration/multi_line_output_modes.html) must be set to either 2, 7 or 9
(2-hanging,  7-noqa, 9-vertical-prefix-from-module-import)

OR set [`include_trailing_comma=true`](https://pycqa.github.io/isort/docs/configuration/options.html#include-trailing-comma) and `multi_line_output` to 2, 3, 5, 7 or 9
(2-hanging, 3-vert-hanging, 5-vert-grid-grouped, 7-noqa, 9-vertical-prefix-from-module-import)

(note: technically multi_line_output=2 + include_trailing_comma=true is broken, but that's an isort issue that can be fixed eventually (see: https://github.com/PyCQA/isort/issues/1864), I've also omitted 6 as it is deprecated)

Any other mode will result in missing trailing comma or indentation that conflicts with this tool.

**Comment by asottile** [comment]
I don't think repeating isort's docs here is productive or useful
