### ISSUE TITLE
Add support for Jupyter notebooks?

### ISSUE THREAD

**Issue by cyyc1** [asottile/add-trailing-comma#204]
Hi, would it be possible to provide support for Jupyter notebooks?

`black` offers a Jupyter pre-commit hook, but its trailing comma strategy is different from this tool's, because it doesn't add trailing commas when there's only one line of arguments:

```python
some_function(
    arg1, arg2, arg3
)
```

**Comment by asottile** [comment]
no thanks, I have no interest in trying to support that

**Comment by cyyc1** [comment]
Then I assume you'd have no problem of me creating a separate tool that reuses a lot of the code from this tool? I would cite licenses and everything for sure.
