### ISSUE TITLE
An option to disable de-indent of braces

### ISSUE THREAD

**Issue by Prometheus3375** [asottile/add-trailing-comma#228]
In my organization we are using codestyle with dangling braces:

```python
data = {
    'key1': 1,
    'key2': 2,
    'key3': 3,
    }

val = 1
```

The reasoning behind this style is pretty simple: if there is a char in the first column, then there is a variable declaration, block statement, function call, etc., and everything till next char in the first column belongs to this statement. Such approach is pretty useful, for example, in constants module: quickly scroll file to locate constant of interest just by looking at first column and braces wont mess up view.

In addition to the above, some text editors have different collapsing. For example, in Notepad++:
With indent:
![image](https://github.com/asottile/add-trailing-comma/assets/35541026/62991d99-2b35-4675-9b06-399f3b0cace6)
Without indent:
![image](https://github.com/asottile/add-trailing-comma/assets/35541026/725256f1-b270-4dcf-baee-760541726661)

We would like to use add-trailing-comma to automatically add trailing commas as well as other features you implemented except for de-indention of braces. Do you have plans to add options to customize the behavior of the script? And why you decided to add this feature to this package?

**Comment by asottile** [comment]
no

the whole point if this is there is _one way to do it_

if you don't like the style, don't use the tool
