### ISSUE TITLE
Provide a Docker image

### ISSUE THREAD

**Issue by Bengt** [asottile/add-trailing-comma#263]
I would like to use this tool as a linter in my CI/CD pipelines. To that end, I would like to use an official docker image from your side instead of creating my own or installing the tool on each run.

**Comment by asottile** [comment]
it would require me to make and maintain n images for each python version which amount to just `pip install`.

you're better to make your own

**Comment by Bengt** [comment]
I see that providing images is an additional effort. The alternative to you maintaining n images is, that m users like me maintain m * n images, which is even more effort. Because having a central source for images is preferable, projects like cytopia and pipeline-components provide them for some software packages. However, it would be much nicer if the software projects would each provide their images directly.

**Comment by asottile** [comment]
if you want to pay me to maintain stuff for a platform by all means. but I'm not doing it for free
