### ISSUE TITLE
Affects python f-strings

### ISSUE THREAD

**Issue by pohmelie** [asottile/add-trailing-comma#276]
Version: 3.1.0

Here is the diff
```diff
-    print(f"{len(binance_futures_bars_1m) = }")
+    print(f"{len(binance_futures_bars_1m) =}")
```

**Comment by asottile** [comment]
seems right to me

**Comment by pohmelie** [comment]
Seems that this this changes the ouput string. What if I want `len(binance_futures_bars_1m = 666` instead of `len(binance_futures_bars_1m =666` in my stdout? This pre commit hook should not affect the code behavior.

**Comment by asottile** [comment]
I would never write code like that so I don't particularly care.  if you want to write a tested PR which "fixes" this by all means go ahead -- but as I see it this is a "garbage in garbage out" scenario so I don't really view it as broken

**Comment by pohmelie** [comment]
So, you name a python f-string feature a «garbage»? Ask anyone on the earth what is better as output for python debug log `x =1` or `x = 1`?

**Comment by asottile** [comment]
personally I'd use a debugger -- if I wanted a debug-fstring I'd use `print(f'{len(whatever)=}')`
