### ISSUE TITLE
autopep8 and add-trailing-comma fight over indentation

### ISSUE THREAD

**Issue by chriskuehl** [asottile/add-trailing-comma#32]
Here's an (admittedly poorly-formatted) reproduction. FWIW I prefer add-trailing-comma's approach, but curious to hear your thoughts. This is obviously weird indentation but ideally they wouldn't fight. Do we need to make autopep8 smarter?

## what add-trailing-comma wants
```python
[a()
    for b in c
    if (
        d
    )
]
```

## what autopep8 wants
```python
[a()
    for b in c
    if (
        d
)
]
```

**Comment by asottile** [comment]
I kind of expect this to happen too:

```diff
-[a()
+[
+    a()
     for b in c
     if (
         d
     )
 ]
```

I'll see what I can do to make that so
