### ISSUE TITLE
Unable to run against all files

### ISSUE THREAD

**Issue by nficano** [asottile/add-trailing-comma#37]
I wanted to do this over my entire codebase, but when I run:

```bash
pre-commit run --all-files
```

it returns ``(no files to check) Skipped``

**Comment by asottile** [comment]
Can you produce the entire output, as well as `git ls-files -- '*.py'`?

**Comment by nficano** [comment]
disregard this one actually, user error. 😞 thanks for the great hook sir!

**Comment by asottile** [comment]
Cheers :D
