### ISSUE TITLE
False negative with statement ending with parens

### ISSUE THREAD

**Issue by asottile** [asottile/add-trailing-comma#42]
```python
if (foo and
    bar()):
    pass
```

I expect to be rewritten to

```python
if (
    foo and
    bar()
):
    pass
```

But I imagine the same code that prevents this from being rewritten is firing:

```python
foo('bar {}'.format(
    'baz',
))
```

which I don't think should be rewritten.

Need to come up with a more clever heuristic here.

**Comment by asottile** [comment]
Should or shouldn't? The second is consistent with the style.

**Comment by smagafurov** [comment]
The first is also consistent with the style.
And therefore shouldn't be rewritten.

**Comment by asottile** [comment]
It is not, the style prescribes no hugging braces (unless on a line with only braces)

**Comment by smagafurov** [comment]
sadly...

**Comment by asottile** [comment]
No not sadly, that's how this tool is designed. If you don't like that style, don't use the tool! :laughing:

This issue is about making _more_ constructs get rewritten in that way

**Comment by smagafurov** [comment]
This tool is very useful
So it is sadly :)

Because I really find this style useful:
```
async def test_ambiguous(api_request):
    response = await api_request('some_method', some_param='some-value')
    assert response['error'] == {
        'code': 6001,
        'message': 'Validation error',
        'data': {'errors': [
            {'code': 'ambiguous', 'message': 'Ambiguous'},
        ]}
    }
```
I don't want to expand this line `'data': {'errors': [` because it has no "semantic value".

**Comment by asottile** [comment]
Tough! The tool can't possibly determine """semantic vslue"""

I don't know what to tell you

**Comment by smagafurov** [comment]
oops...

This case works fine for me

```
async def test_ambiguous(api_request):
    response = await api_request('some_method', some_param='some-value')
    assert response['error'] == {
        'code': 6001,
        'message': 'Validation error',
        'data': {'errors': [
            {'code': 'ambiguous', 'message': 'Ambiguous'},
        ]}
    }
```

add-trailing-comma doesn't touch it!

Problem is only with this

```
bankrupts = [{
    'id': company.bankrupt_id,
    'type': 'company',
} for company in found_companies]
```

**Comment by asottile** [comment]
Look, I think you're missing the point. The whole goal of the tool is so you _don't argue about style_.

**Comment by smagafurov** [comment]
The tool just shouldn't touch this case
```
bankrupts = [{
    'id': company.bankrupt_id,
    'type': 'company',
} for company in found_companies]
```
And also shouldn't touch this case too
```
bankrupts = [
    {
        'id': company.bankrupt_id,
        'type': 'company',
    } for company in found_companies
]
```
They are both valid

A person can choose according to "semantic value"

**Comment by asottile** [comment]
I'm sorry, the first one is ugly and will continue to be rewritten.  Please stop

**Comment by smagafurov** [comment]
PyCharm Reformat Code works exactly that way
https://www.jetbrains.com/help/pycharm/reformatting-source-code.html

**Comment by smagafurov** [comment]
Very sorry for inattention.
I did not notice that you are the author of the tool.
:)
Sorry one more time...
And thank for the tool!
