### ISSUE TITLE
Is it possible to disable whitespace editing?

### ISSUE THREAD

**Issue by srcreigh** [asottile/add-trailing-comma#45]
I would like to use add-trailing-comma to add trailing commas to a file. However add-trailing-commas also adds and removes whitespace. Is it possible to disable whitespace editing?

**Comment by asottile** [comment]
It's not possible to enforce the style without whitespace editing. Is there a particular problematic transformation you're hitting?

**Comment by srcreigh** [comment]
I was interested in using add-trailing-comma in conjunction with `yapf`, since yapf doesn't add trailing commas. I didn't realize that I could run add-trailing-comma then `yapf` to get trailing commas + `yapf` formatting. Thanks for the quick reply!
