### ISSUE TITLE
One more case with parens

### ISSUE THREAD

**Issue by smagafurov** [asottile/add-trailing-comma#58]
This code ...
```
bankrupts = [{
    'id': company.bankrupt_id,
    'type': 'company',
} for company in found_companies]
```

... shouldn't be rewritten (IMHO) with:
```
bankrupts = [
    {
        'id': company.bankrupt_id,
        'type': 'company',
    } for company in found_companies
]
```

And vice versa

They are both valid

Also this similar case already works exactly that way, the tool doesn't touch it:
```
assert response['error'] == {
    'data': {'errors': [
        {'code': 'code1', 'message': 'message1'},
        {'code': 'code2', 'message': 'message2'},
    ]},
}
```

**Comment by asottile** [comment]
Please cease and desist.  This is not up for debate.

**Comment by smagafurov** [comment]
Very sorry for inattention.
I did not notice that you are the author of the tool.
:)
Sorry one more time...
And thank for the tool!
