### ISSUE TITLE
[regression][Python 3.8] Breaks single-arg generator expressions

### ISSUE THREAD

**Issue by webknjaz** [asottile/add-trailing-comma#99]
So I've upgraded Python in jobs where I run linters (and pre-commit in particular) from Python 3.7 to Python 3.8 and it started breaking the generator expressions that are the only args passed into function calls.
I confirmed locally that setting Python 3.7 fixes the behavior and Python 3.8 breaks it.

To give an example, here's a dict construction code that `add-trailing-comma` preserves when running under Python 3.7
```python
return dict(
    (gw.version, gw)
    for gw in cls.__subclasses__()
)
```
But under Python 3.8, it breaks the syntax like this:
```diff
 return dict(
     (gw.version, gw)
-    for gw in cls.__subclasses__()
+    for gw in cls.__subclasses__(),
 )
```
It's not a style complaint. It breaks the AST parser and makes it non-runnable because generator expressions
have to be enclosed with braces. And should one add a comma, implying more args passed to the function, they'd have to wrap the generator expression using an extra pair of parentheses (that can be omitted when there's only one arg and no comma).

Ref: https://github.com/cherrypy/cheroot/runs/890705032#step:9:122

**Comment by asottile** [comment]
you must be using an ancient version of add-trailing-comma, this was fixed years ago

**Comment by webknjaz** [comment]
Yeah, you're right. I missed that. Thanks!
